# No version number needed for Compose V2
services:
  music-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./.env:/app/.env:ro  # Read-only mount for security
      - ./youtube_cookies.txt:/app/youtube_cookies.txt:ro  # Read-only mount for cookies
    ports:
      - "${DASHBOARD_PORT:-8080}:${DASHBOARD_PORT:-8080}"  # Dashboard port (defaults to 8080)
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - DASHBOARD_PORT=${DASHBOARD_PORT:-8080}
      - DASHBOARD_URL_PREFIX=${DASHBOARD_URL_PREFIX:-/musho}
      - DEFAULT_VOLUME=${DEFAULT_VOLUME:-0.2}
      - MAX_SONG_LENGTH=${MAX_SONG_LENGTH:-7200}
      - PROXY_URL=${PROXY_URL:-}
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    # Healthcheck to monitor the container status
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:${DASHBOARD_PORT:-8080}${DASHBOARD_URL_PREFIX:-/musho}/')"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    # Security settings
    security_opt:
      - no-new-privileges:true 