version: '3'

services:
  musicbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-musicbot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./downloads:/app/downloads
      - ./youtube_cookies.txt:/app/youtube_cookies.txt
    environment:
      - TZ=UTC
    env_file:
      - .env
    # The extra_hosts setting helps Docker connect to host machine services
    extra_hosts:
      - "host.docker.internal:host-gateway"