version: '3'

services:
  musicbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-musicbot
    restart: unless-stopped
    privileged: true
    volumes:
      - ./logs:/app/logs
      - ./downloads:/app/downloads
      - ./youtube_cookies.txt:/app/youtube_cookies.txt
      - ./.spotify-cache:/root/.spotify-dlp
      - ./templates:/app/templates
      - ./static:/app/static
      - ./data:/app/data
    ports:
      - "8080:80"
    environment:
      - TZ=UTC
      - DASHBOARD_PORT=8080
      - DASHBOARD_URL_PREFIX=/musho
    env_file:
      - .env
    # Resource constraints to prevent container from using too much system resources
    mem_limit: 2G
    memswap_limit: 2G
    # Healthcheck to monitor container health
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os.path.exists('/app/logs')"]
      interval: 30s
      timeout: 10s
      retries: 3